web_page_archive.capture_utility.wpa_html_capture:
  type: mapping
  label: 'HTML Capture utility'
  mapping:
    capture:
      type: boolean
      label: 'Capture?'

web_page_archive.wpa_html_capture.settings:
  type: config_object
  label: 'HTML Capture Utility settings'
  mapping:
    defaults:
      type: mapping
      mapping:
        capture:
          type: boolean
          label: 'Capture?'

web_page_archive.comparison_utility_settings.wpa_html_diff_compare:
  type: string
  label: 'HTML Diff'
