<?php

/**
 * @file
 * This module holds functions useful for web page archives.
 */

use Drupal\web_page_archive\Entity\WebPageArchiveTypeInfo;

/**
 * Implements hook_entity_type_alter().
 */
function web_page_archive_entity_type_alter(array &$entity_types) {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(WebPageArchiveTypeInfo::class)
    ->entityTypeAlter($entity_types);
}

/**
 * Implements hook_entity_operation().
 */
function web_page_archive_entity_operation($entity) {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(WebPageArchiveTypeInfo::class)
    ->entityOperation($entity);
}
