web_page_archive.settings:
  type: config_object
  label: 'Web page archive settings'
  mapping:
    system:
      type: mapping
      mapping:
        node_path:
          type: string
          label: 'NodeJS path'
        npm_path:
          type: string
          label: 'npm path'
    cron:
      type: mapping
      mapping:
        capture_max:
          type: integer
          label: 'Capture Max'
        file_cleanup:
          type: integer
          label: 'File Cleanup'
    comparison:
      type: mapping
      mapping:
        run1:
          type: integer
          label: 'Run ID #1'
        run2:
          type: integer
          label: 'Run ID #2'
        strip_type:
          type: string
          label: 'Strip Type'
        strip_patterns:
          type: string
          label: 'Strip Patterns'
        comparison_utilities:
          type: sequence
          label: 'Comparison Utilities'
          sequence:
            type: web_page_archive.comparison_utility_settings.[%key]
    defaults:
      type: mapping
      mapping:
        id:
          type: string
          label: 'ID'
        label:
          type: label
          label: 'Label'
        uuid:
          type: string
        url_type:
          type: string
          label: 'URL Type'
        urls:
          type: string
          label: 'URLs'
        user_agent:
          type: string
          label: 'User Agent'
        use_robots:
          type: boolean
          label: 'Honor robots.txt restrictions'
        use_cron:
          type: boolean
          label: 'Use Cron?'
        cron_schedule:
          type: string
          label: 'Cron Schedule'
        timeout:
          type: integer
          label: 'Timeout (ms)'

web_page_archive.web_page_archive.*:
  type: config_entity
  label: 'Web Page Archive config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    url_type:
      type: string
      label: 'URL Type'
    urls:
      type: string
      label: 'URLs'
    user_agent:
      type: string
      label: 'User Agent'
    use_robots:
      type: boolean
      label: 'Honor robots.txt restrictions'
    use_cron:
      type: boolean
      label: 'Use Cron?'
    cron_schedule:
      type: string
      label: 'Cron Schedule'
    timeout:
      type: integer
      label: 'Timeout (ms)'
    capture_utilities:
      type: sequence
      sequence:
        type: mapping
        mapping:
          id:
            type: string
          data:
            type: web_page_archive.capture_utility.[%parent.id]
          weight:
            type: integer
          uuid:
            type: string
    run_entity:
      type: string
      label: 'Run Entity'

web_page_archive.capture_utility.*:
  type: mapping
  label: 'Capture utility settings'

field.widget.settings.web_page_archive_capture_widget:
  type: mapping
  label: 'Capture widget settings'
  mapping:
    size:
      type: integer
      label: 'Size'
    placeholder:
      type: string
      label: 'Placeholder'

views.filter.web_page_archive_capture_utility_filter:
  type: views_filter
  label: 'Web page archive capture utility filter'
  mapping:
    operator:
      type: string
      label: 'Operator'
    value:
      type: sequence
      label: 'Values'
      sequence:
        type: string
        label: 'Value'
    expose:
      type: mapping
      label: 'Expose'
      mapping:
        reduce:
          type: integer
          label: 'Reduce'
    group_info:
      mapping:
        group_items:
          sequence:
            type: views.filter.group_item.in_operator
            label: 'Group item'

views.filter.web_page_archive_compare_response_filter:
  type: views_filter
  label: 'Web page archive compare response filter'
  mapping:
    operator:
      type: string
      label: 'Operator'
    value:
      type: sequence
      label: 'Values'
      sequence:
        type: string
        label: 'Value'
    expose:
      type: mapping
      label: 'Expose'
      mapping:
        reduce:
          type: integer
          label: 'Reduce'
    group_info:
      mapping:
        group_items:
          sequence:
            type: views.filter.group_item.in_operator
            label: 'Group item'

views.field.web_page_archive_serialized_capture:
  type: views_field
  label: 'Serialized Capture Results'
  mapping:
    format:
      type: string
      label: 'Display format'
    key:
      type: string
      label: 'Which key should be displayed'

views.field.web_page_archive_serialized_comparison_results:
  type: views_field
  label: 'Serialized Comparison Results'
  mapping:
    format:
      type: string
      label: 'Display format'
    key:
      type: string
      label: 'Which key should be displayed'

web_page_archive.comparison_utility_settings.web_page_archive_file_size_compare:
  type: string
  label: 'File Size'
