<?php

/**
 * @file
 * This module holds functions useful for screenshot capturing functionality.
 */

 use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function wpa_screenshot_capture_theme($existing, $type, $theme, $path) {
  return [
    'wpa_screenshot_compare' => [
      'variables' => ['left' => NULL, 'right' => NULL],
    ],
  ];
}

/**
 * Implements hook_views_pre_render().
 */
function wpa_screenshot_capture_views_pre_render(ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'web_page_archive_run_comparison_summary')) {
    $view->element['#attached']['library'][] = 'wpa_screenshot_capture/wpa-slider';
  }
}
